### ISSUE TITLE
Status of Open Sensor Platform

### ISSUE THREAD

**Issue by Timonsc** [sensorplatforms/open-sensor-platform#3]
Hi guys,

What is the status of the Open Sensor Platform? What is the reason of the redirect of your website listed on the github page.

Regards Timon

**Comment by riansanderson** [comment]
The development of OSP is active again.

There's been quite a bit of corporate turmoil with first the acquisition of Sensor Platforms by Audience, then the pending acquisition of Audience by Knowles. However we are now past all that. 

I'll be releasing the roadmap with plans and a reboot of the repository within the next week. You're going to start seeing commits very soon.

**Comment by Timonsc** [comment]
Great! Thanks for the reply. I'll follow the development of the project.
